### ISSUE TITLE
Configure stryker mutation score badge

### ISSUE THREAD

**Issue by Ocramius** [psr7-sessions/storageless#135]
The badge in `README.md` does not work yet.
I need someone else to head to https://dashboard.stryker-mutator.io/ and configure the API keys for it (https://infection.github.io/guide/mutation-badge.html#main) in the repository secrets (https://github.com/psr7-sessions/storageless/settings/secrets).

The two environment variables are called `INFECTION_BADGE_API_KEY` and `STRYKER_DASHBOARD_API_KEY`.

Sadly, stryker is quite broken for me (doesn't consider me an admin of this organisation: possibly due to github API pagination :shrug: )

**Comment by lcobucci** [comment]
@Ocramius I just configured the secret `INFECTION_BADGE_API_KEY`, because according to infection's docs we just need one of them:

> Provide the API key for your project as a secret environment variable - either INFECTION_BADGE_API_KEY or STRYKER_DASHBOARD_API_KEY can be used.

**Comment by Ocramius** [comment]
Yes, I usually provide both for forward compatibility, since I don't know which one will survive :D

**Comment by Ocramius** [comment]
Closing here meanwhile, thanks @lcobucci!

**Comment by lcobucci** [comment]
https://github.com/psr7-sessions/storageless/blob/4f860bf07ff1871a9ed333e16e4b5e56831e1705/infection.json.dist#L10 looks wrong though...

**Comment by Ocramius** [comment]
#196 😁
