### ISSUE TITLE
Configure automatic releases secrets

### ISSUE THREAD

**Issue by Ocramius** [psr7-sessions/storageless#136]
In https://github.com/psr7-sessions/storageless/blob/9ff0c88a0fe27facb29a9588989c219aa8d9692e/.github/workflows/release-on-milestone-closed.yml#L44, we require an `ORGANIZATION_ADMIN_TOKEN` and a `SIGNING_SECRET_KEY`.

Both need to be provided by an admin of the organisation.

I'll search for my GPG master key ASAP, since it's somewhere in my boxes (after having moved, things got messy :P )

**Comment by Ocramius** [comment]
Done (found the damn key, generated a scoped subkey :D )

**Comment by morozov** [comment]
> generated a scoped subkey

Could you elaborate somewhere on how exactly it's done and how it should be registered on GH?

E.g. I have my primary key and I generated a signing subkey:
```
$ gpg --expert --edit-key 0x...

gpg> addkey
...
gpg> save
```
Do I need to add another public key to my GH account if I want to release as myself? How do I export the subkey and in which format should I create the `SIGNING_SECRET_KEY` variable?

**Comment by Ocramius** [comment]
Can you open an issue on `laminas/automatic-releases`?

The `gpg --armor --export-secret-subkeys aabbccddeeff!` command (exclamation mark included) gives you an ascii subkey: you put that in the contents of the `SIGNING_SECRET_KEY` under your repository or organisation secrets.

After generating a new subkey, you will need to export your **public** key (`gpg --armor --export $yourMainKey`) and add it under your account.

Note that GitHub doesn't seem to update pre-existing subkeys, so you probably need to delete and re-add it.

**Comment by morozov** [comment]
Sounds doable. Thanks! Here's the issue: https://github.com/laminas/automatic-releases/issues/32.
