### ISSUE TITLE
Provide installation methods for different frameworks

### ISSUE THREAD

**Issue by Ocramius** [psr7-sessions/storageless#15]
Maybe it is time to split `README.md`?

**Comment by 3DFace** [comment]
Not sure if it's appropriate thread to ask...
Is it possible to use this library without frameworks/PSR-7-middleware at all? Some base class that I can instantiate and call get- set- on it? It would be nice to have an explanation how to use it in such scenarios if it's possible.

**Comment by Ocramius** [comment]
This lib is primarily designed to be used within a PSR-7 middleware
context, but all classes can be used manually on their own. They are
actually tending to be tiny and simple to import.

**Comment by Ocramius** [comment]
Closing here: won't do, as PSR-15 is now well established
