### ISSUE TITLE
Re-configure infection to push mutation score reports for all stable branches

### ISSUE THREAD

**Issue by Ocramius** [psr7-sessions/storageless#196]
See https://github.com/psr7-sessions/storageless/runs/3742041520?check_suite_focus=true#step:8:56, which reports:

```
Warning:  Dashboard report has not been sent: Branch "8.3.x" does not match expected badge configuration
```

This has been made configurable in https://github.com/infection/infection/pull/1538, and released in https://github.com/infection/infection/releases/tag/0.24.0

We'll need to adjust some configuration for it to work properly with the new branch naming mechanism :-)

**Comment by Ocramius** [comment]
Badge will likely never work, because the branch name constantly changes :thinking:

**Comment by lcobucci** [comment]
> Badge will likely never work, because the branch name constantly changes 🤔

I reckon we can use a regex.. something like `/\d\.\d\.x/` should suffice, the tricky bit is keeping `README` up to date.

**Comment by Ocramius** [comment]
IMO worth having this as badge feature request instead 😬

**Comment by Ocramius** [comment]
Handled in https://github.com/psr7-sessions/storageless/commit/57bb1dfc7268f25221efce8e4d07543f6b333917
