### ISSUE TITLE
Storing non-`JsonSerializable` data in a session container should make it scream

### ISSUE THREAD

**Issue by Ocramius** [psr7-sessions/storageless#23]
Maybe we should reject anything that isn't `JsonSerializable` to avoid "wtf moments"?

**Comment by danizord** [comment]
:+1:

**Comment by Slamdunk** [comment]
This has been addressed by https://github.com/psr7-sessions/storageless/commit/2662210c148111faa535f5f655b48e139a309ff3 (any many commits before and after)
