### ISSUE TITLE
Functional/immutable approach to session containers

### ISSUE THREAD

**Issue by Ocramius** [psr7-sessions/storageless#28]
Currently, the session middleware is designed to inject a _mutable_ session container into the `ServerRequestInterface` attributes.

While this approach is highly usable, it doesn't really compose well with functional approaches, and it breaks the `ServerRequestInterface` immutability by design (this choice is conscious).

Here's what the current approach looks like:

``` php
function myMiddleware(ServerRequestInterface $request, ResponseInterface $response) : ResponseInterface
{
    $session = $request->getAttribute(SessionMiddleware::SESSION_ATTRIBUTE);
    $session->set('counter', $session->get('counter', 0) + 1);

    // .. go on

    return $response;
}
```

In a functional/immutable world, this would become:

``` php
$sessionInjector = new SomeSortOfInjector($cryptoConfig);

function myMiddleware(ServerRequestInterface $request, ResponseInterface $response) use ($sessionInjector) : ResponseInterface
{
    $session = $request->getAttribute(SessionMiddleware::SESSION_ATTRIBUTE);
    $session = $session->with('counter', $session->get('counter', 0) + 1);

    // .. go on

    return $sessionInjector->responseWithSession($response, $session);
}
```

Just a suggestion, but I don't want folks to think "OH EM GEE, THAT LIBRARY BREAKS IMMUTABILITY!"
The mutable approach was consciously picked due to ease of use, but the functional approach is still viable and may be implemented if there is some interest or some strong use-case for it.

**Comment by danizord** [comment]
OH EM GEE, THAT LIBRARY BREAKS IMMUTABILITY! :trollface: 

Seriously, that really breaks message immutability, but while that approach brings some mutability drawbacks, it's not a PSR-7 violation at all, since [PSR-7 allows mutable attributes](https://github.com/php-fig/http-message/blob/f22d9b6dd24ec003c7996813d505e4a9b1b6390d/src/ServerRequestInterface.php#L206). So I still prefer the "convenient" way in this case.

**Comment by Ocramius** [comment]
Yeah, and I also don't want to manually write the session in every middleware anyway :-)

**Comment by Slamdunk** [comment]
I think this has been discussed enough in https://github.com/psr7-sessions/storageless/issues/60 too to make it a https://github.com/psr7-sessions/storageless/labels/wontfix
