### ISSUE TITLE
Question: PHP minimum version

### ISSUE THREAD

**Issue by juliangut** [psr7-sessions/storageless#56]
Is there a reason why minimum required PHP version is `~7.0`? couldn't it be `>=5.5`?

**Comment by juliangut** [comment]
I've just seen #29, I expand my question:

Is there any "technical" reason to force minimum PHP version to `~7.0`? maybe `>=5.6`

IMHO I don't see the point in not wanting to support lets say a "legacy version" when it seems technically feasible (only scalar type hinting being used?) given PHP5.6 is still [actively supported](http://php.net/supported-versions.php) and will still be maintained for two more years

**Comment by Ocramius** [comment]
Not interested, and will likely bump to 7.1 as soon as we have any nullable
or void type declaration.

7.0 is stable, there are 0 reasons not to use it for new packages and
projects.

Security support is already something complex to take on: let's not turn it
into security+ legacy support.
