### ISSUE TITLE
Upgrade lcobucci/jwt to v4

### ISSUE THREAD

**Issue by lcobucci** [psr7-sessions/storageless#61]
Since it's very close to be released we can already start doing it

**Comment by Ocramius** [comment]
@lcobucci try an example patch - would also serve as a good example to see whether the new JWT API plays nicely.

**Comment by lcobucci** [comment]
@Ocramius will do 😉

**Comment by Ocramius** [comment]
Removing milestone: `4.0.0` of `lcobucci/jwt` is not yet in sight.

**Comment by Ocramius** [comment]
Handled in #146
