### ISSUE TITLE
Support for zend-expressive 2.0 (zend-stratigility 2.0)

### ISSUE THREAD

**Issue by belgattitude** [psr7-sessions/storageless#62]
Is there support planned for zend-expressive 2.0 ?

Any ideas on how to do it ?

**Comment by Ocramius** [comment]
PSR-15 isn't final yet: once that reaches 1.0.0 we can adapt to it.

**Comment by lcobucci** [comment]
It would be addressed in #59 since expressive 2 follows PSR-15.

**Comment by belgattitude** [comment]
Got it, thanks @Ocramius.
