### ISSUE TITLE
Composer dependencies are not installable

### ISSUE THREAD

**Issue by lferro9000** [psr7-sessions/storageless#69]
Current composer dependencies are not instalable generating the following error:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for humbug/humbug dev-master -> satisfiable by humbug/humbug[dev-master].
    - humbug/humbug dev-master requires phpunit/phpunit ^6.0 -> satisfiable by phpunit/phpunit[6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9, 6.0.x-dev, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.x-dev, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4, 6.2.x-dev, 6.3.0, 6.3.x-dev, 6.4.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by Ocramius** [comment]
Update: `humbug/humbug` is deprecated - we should switch to `infection/infection`.

**Comment by Ocramius** [comment]
Solved in 4.0.0
